QUIT_KEY: str = "q"
SCROLL_UP_KEY: str = "k"
SCROLL_DOWN_KEY: str = "j"
NEXT_INPUT_KEY: str = "n"

PROMPT_DIVISOR: str = ">"
UNPROMPTED_INDICATOR: str = "(?)"

CONTENT_PADDING: int = 2

SCROLLING_TEXT_SIZE: int = 12
